[build]
  command = "npm run build"
  publish = ".output/public" # Keep this as .output/public (assuming static assets are here)

[functions]
  # CHANGE THIS: Point directly to the folder containing index.mjs
  directory = ".output/server/chunk" 

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true